expname: generic
basedir: manifold://compphoto_models/tree/x3d.nerf.training.workflow
datadir: manifold://compphoto_data/tree/cvd_siggraph_2020/
testdir: manifold://compphoto_data/tree/implicit/nerf/test/
localdir: /var/svcscm/local/test/
tblogdir: manifold://compphoto_tb_logs/tree/proto/x3d.nerf.training.workflow
dataset_type: cvd
depth_stream: DF/1
color_stream: down

factor: 5
llffhold: 8
render_only: False
render_test: False
N_rand: 1024
N_samples: 128
N_importance: 0

concat_times_views: False
train_stereo: False
use_viewdirs: False
use_times: True
use_sf: False
raw_noise_std: 1
no_batching: True
no_ndc: True
lindisp: True
spherify: False
